# Generated by Django 3.2 on 2021-05-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('primarykey', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sellername', models.CharField(max_length=122, null=True)),
                ('itemname', models.CharField(max_length=122, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('description', models.TextField()),
                ('email', models.CharField(max_length=300, null=True)),
                ('price', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
